[package]
name = "kitty"
version = "0.0.0"
description = "A Tauri App"
authors = ["you"]
license = ""
repository = ""
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "kitty_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.0.0-alpha", features = [] }
anyhow = { version = "1", features = ["backtrace"] }
reqwest = { version = "0.11.22", features = ["blocking"] }
build-target = "0.4.0"

[dependencies]
tauri = { version = "2.0.0-alpha", features = ["tray-icon", "icon-ico"] }
tauri-plugin-window = "2.0.0-alpha"
tauri-plugin-shell = "2.0.0-alpha"
serde_json = "1.0"
serde = "1.0.193"
rusqlite = "0.30.0"
sea-orm = { version = "0.12", features = [
  "sqlx-sqlite",
  "runtime-tokio-rustls",
  "macros",
] }
entity = { path = "./entity" }
migration = { path = "./migration" }
tokio = { version = "1.34.0", features = ["macros"] }
tauri-plugin-process = "2.0.0-alpha"
thiserror = "1.0.50"
anyhow = "1"
uuid = { version = "1.6.1", features = ["v4"] }
libc = "0.2.151"
sysproxy = "0.3.0"
winapi = { version = "0.3", features = ["winuser"] }
futures = "0.3.29"
async-trait = "0.1.74"
tauri-plugin-autostart = "2.0.0-alpha"


[workspace]
members = [".", "migration", "entity"]

[features]
# this feature is used for production builds or when `devPath` points to the filesystem
# DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features = ["winuser"] }
kernel32-sys = "0.2.2"
